#pragma once
#include <string>
using namespace std;

#define ZOMBIE_SHEET_DIRECTORY rand(ZOMBIE_WALK1_DIRECTORY, ZOMBIE_WALK2_DIRECTORY)
#define NUMBER_OF_ZOMBIE_MOVING_SHEET 2

enum ImageType
{
    NULL_DIRECTORY = -1,

    // Plant seed
    PEASHOOTER_DIRECTORY,
    PEASHOOTER_SHEET_DIRECTORY,
    PEASHOOTER_SHEET_BLINK_DIRECTORY,
    PEASHOOTER_ATTACK_DIRECTORY,
    PEASHOOTER_ATTACK_BLINK_DIRECTORY,

    SUNFLOWER_DIRECTORY,
    SUNFLOWER_SHEET_DIRECTORY,
    SUNFLOWER_SHEET_BLINK_DIRECTORY,
    SUNFLOWER_HAPPY_DIRECTORY,
    SUNFLOWER_HAPPY_BLINK_DIRECTORY,

    WALNUT_DIRECTORY,
    WALNUT_1_DIRECTORY,
    WALNUT_2_DIRECTORY,
    WALNUT_3_DIRECTORY,
    WALNUT_4_DIRECTORY,
    WALNUT_1_BLINK_DIRECTORY,
    WALNUT_2_BLINK_DIRECTORY,
    WALNUT_3_BLINK_DIRECTORY,
    WALNUT_4_BLINK_DIRECTORY,

    SNOWPEA_DIRECTORY,
    SNOWPEA_SHEET_DIRECTORY,
    SNOWPEA_ATTACK_DIRECTORY,

    PEASHOOTER_ICON_BRIGHT_DIRECTORY,
    PEASHOOTER_ICON_DIM_DIRECTORY,
    SUNFLOWER_ICON_BRIGHT_DIRECTORY,
    SUNFLOWER_ICON_DIM_DIRECTORY,
    WALNUT_ICON_BRIGHT_DIRECTORY,
    WALNUT_ICON_DIM_DIRECTORY,
    SNOWPEA_ICON_BRIGHT_DIRECTORY,
    SNOWPEA_ICON_DIM_DIRECTORY,

    PEA_DIRECTORY,
    PEA_EXPLODE_DIRECTORY,
    SNOWZ_PEA_DIRECTORY,
    SNOWZ_PEA_EXPLODE_DIRECTORY,

    STARTING_SCREEN_DIRECTORY,
    CHOOSE_LEVELS_DIRECTORY,
    BACKGROUND_DIRECTORY,
    BACKGROUND_LV1_DIRECTORY,
    BACKGROUND_LV2_DIRECTORY,
    LOSING_MESSAGE_DIRECTORY,
    WINNING_MESSAGE_DIRECTORY,

    SUN_DIRECTORY,
    SUN_BAR_DIRECTORY,
    ICON_BAR_DIRECTORY,
    SHOVEL_BAR_DIRECTORY,
    SHOVEL_DIRECTORY,
    MENU_ICON_DIRECTORY,
    MENU_DIRECTORY,
    CONTINUE_DIRECTORY,

    ZOMBIE_WALK1_DIRECTORY,
    ZOMBIE_WALK2_DIRECTORY,
    ZOMBIE_WALK1_BLINK_DIRECTORY,
    ZOMBIE_WALK2_BLINK_DIRECTORY,
    ZOMBIE_DIE_DIRECTORY,
    ZOMBIE_HEAD_DIRECTORY,
    ZOMBIE_EATING_DIRECTORY,
    ZOMBIE_EATING_BLINK_DIRECTORY,

    CONE_ZOMBIE_WALK_DIRECTORY,
    CONE_ZOMBIE_WALK_BLINK_DIRECTORY,
    CONE_ZOMBIE_EATING_DIRECTORY,
    CONE_ZOMBIE_EATING_BLINK_DIRECTORY,

    BUCKET_ZOMBIE_WALK_DIRECTORY,
    BUCKET_ZOMBIE_WALK_BLINK_DIRECTORY,
    BUCKET_ZOMBIE_EATING_DIRECTORY,
    BUCKET_ZOMBIE_EATING_BLINK_DIRECTORY,

    START_READY_DIRECTORY,
    START_SET_DIRECTORY,
    START_PLANT_DIRECTORY,
    BLACK_SCREEN_DIRECTORY,
    HUGE_WAVE_DIRECTORY,

    COUNT_USED_DIRECTORY
};

const string image_directory[] = {
    // Plant sheet
    "./image/Plant_sheet/Peashooter.png",              // PEASHOOTER_DIRECTORY
    "./image/Plant_sheet/peashooter_sheet.png",        // PEASHOOTER_SHEET_DIRECTORY
    "./image/Plant_sheet/peashooter_sheet_blink.png",  // PEASHOOTER_SHEET_BLINK_DIRECTORY
    "./image/Plant_sheet/peashooter_attack.png",       // PEASHOOTER_ATTACK_DIRECTORY
    "./image/Plant_sheet/peashooter_attack_blink.png", // PEASHOOTER_ATTACK_BLINK_DIRECTORY

    "./image/Plant_sheet/Sunflower.png",             // SUNFLOWER_DIRECTORY
    "./image/Plant_sheet/sunflower_sheet.png",       // SUNFLOWER_SHEET_DIRECTORY
    "./image/Plant_sheet/sunflower_sheet_blink.png", // SUNFLOWER_SHEET_BLINK_DIRECTORY
    "./image/Plant_sheet/sunflower_happy.png",       // SUNFLOWER_HAPPY_DIRECTORY
    "./image/Plant_sheet/sunflower_happy_blink.png", // SUNFLOWER_HAPPY_BLINK_DIRECTORY

    "./image/Plant_sheet/Walnut.png",               // WALNUT_DIRECTORY
    "./image/Plant_sheet/Walnut-sheet-1.png",       // WALNUT_1_DIRECTORY
    "./image/Plant_sheet/Walnut-sheet-2.png",       // WALNUT_2_DIRECTORY
    "./image/Plant_sheet/Walnut-sheet-3.png",       // WALNUT_3_DIRECTORY
    "./image/Plant_sheet/Walnut-sheet-4.png",       // WALNUT_4_DIRECTORY
    "./image/Plant_sheet/Walnut-sheet-1_blink.png", // WALNUT_1_BLINK_DIRECTORY
    "./image/Plant_sheet/Walnut-sheet-2_blink.png", // WALNUT_2_BLINK_DIRECTORY
    "./image/Plant_sheet/Walnut-sheet-3_blink.png", // WALNUT_3_BLINK_DIRECTORY
    "./image/Plant_sheet/Walnut-sheet-4_blink.png", // WALNUT_4_BLINK_DIRECTORY

    "./image/Plant_sheet/SnowPea.png",        // SNOWPEA_DIRECTORY
    "./image/Plant_sheet/snowpea_sheet.png",  // SNOWPEA_SHEET_DIRECTORY
    "./image/Plant_sheet/snowpea_attack.png", // SNOWPEA_ATTACK_DIRECTORY

    "./image/Plant_seed/icon_peashooter_100.png",     // PEASHOOTER_ICON_BRIGHT_DIRECTORY
    "./image/Plant_seed/icon_peashooter_100_dim.png", // PEASHOOTER_ICON_DIM_DIRECTORY
    "./image/Plant_seed/icon_sunflower.png",          // SUNFLOWER_ICON_BRIGHT_DIRECTORY
    "./image/Plant_seed/icon_sunflower_dim.png",      // SUNFLOWER_ICON_DIM_DIRECTORY
    "./image/Plant_seed/icon_walnut.png",             // WALNUT_ICON_BRIGHT_DIRECTORY
    "./image/Plant_seed/icon_walnut_dim.png",         // WALNUT_ICON_DIM_DIRECTORY
    "./image/Plant_seed/icon_snowpea.png",            // SNOWPEA_ICON_BRIGHT_DIRECTORY
    "./image/Plant_seed/icon_snowpea_dim.png",        // SNOWPEA_ICON_DIM_DIRECTORY

    "./image/Bullets/Pea/pea.png",               // PEA_DIRECTORY
    "./image/Bullets/Pea/pea_explode.png",       // PEA_EXPLODE_DIRECTORY
    "./image/Bullets/Pea/snowz_pea.png",         // SNOWZ_PEA_DIRECTORY
    "./image/Bullets/Pea/snowz_pea_explode.png", // SNOWZ_PEA_EXPLODE_DIRECTORY

    "./image/Background/Starting_Screen.png", // STARTING_SCREEN_DIRECTORY
    "./image/Background/Choose_levels.png",   // CHOOSE_LEVELS_DIRECTORY
    "./image/Background/Frontyard.png",       // BACKGROUND_DIRECTORY
    "./image/Background/Frontyard_LV1.png",   // BACKGROUND_LV1_DIRECTORY
    "./image/Background/Frontyard_LV2.png",   // BACKGROUND_LV2_DIRECTORY
    "./image/Background/ZombiesWon.png",      // LOSING_MESSAGE_DIRECTORY
    "./image/Background/Winning_Pic.png",     // WINNING_MESSAGE_DIRECTORY

    "./image/Icons/sun.png",       // SUN_DIRECTORY
    "./image/Icons/sun_bar.png",   // SUN_BAR_DIRECTORY
    "./image/Icons/Item_Bar.png",  // ICON_BAR_DIRECTORY
    "./image/Icons/Shovel.png",    // SHOVEL_BAR_DIRECTORY
    "./image/Icons/Shovel2.png",   // SHOVEL_DIRECTORY
    "./image/Icons/menu_icon.png", // MENU_ICON_DIRECTORY
    "./image/Icons/menu.png",      // MENU_DIRECTORY
    "./image/Icons/continue.png",  // CONTINUE_DIRECTORY

    "./image/Zombie/Normal/ZombieWalk1.png",        // ZOMBIE_WALK1_DIRECTORY
    "./image/Zombie/Normal/ZombieWalk2.png",        // ZOMBIE_WALK2_DIRECTORY
    "./image/Zombie/Normal/ZombieWalk1_blink.png",  // ZOMBIE_WALK1_BLINK_DIRECTORY
    "./image/Zombie/Normal/ZombieWalk2_blink.png",  // ZOMBIE_WALK2_BLINK_DIRECTORY
    "./image/Zombie/Normal/Zombie_die.png",         // ZOMBIE_DIE_DIRECTORY
    "./image/Zombie/Normal/Zombie_head.png",        // ZOMBIE_HEAD_DIRECTORY
    "./image/Zombie/Normal/ZombieAttack.png",       // ZOMBIE_EATING_DIRECTORY
    "./image/Zombie/Normal/ZombieAttack_blink.png", // ZOMBIE_EATING_BLINK_DIRECTORY

    "./image/Zombie/Cone/ConeZombieWalk.png",         // CONE_ZOMBIE_WALK_DIRECTORY
    "./image/Zombie/Cone/ConeZombieWalk_blink.png",   // CONE_ZOMBIE_WALK_BLINK_DIRECTORY
    "./image/Zombie/Cone/ConeZombieAttack.png",       // CONE_ZOMBIE_EATING_DIRECTORY
    "./image/Zombie/Cone/ConeZombieAttack_blink.png", // CONE_ZOMBIE_EATING_BLINK_DIRECTORY

    "./image/Zombie/Bucket/BucketZombieWalk.png",         // BUCKET_ZOMBIE_WALK_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieWalk_blink.png",   // BUCKET_ZOMBIE_WALK_BLINK_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieAttack.png",       // BUCKET_ZOMBIE_EATING_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieAttack_blink.png", // BUCKET_ZOMBIE_EATING_BLINK_DIRECTORY

    "./image/Announcement/StartReady.png", // START_READY_DIRECTORY
    "./image/Announcement/StartSet.png",   // START_SET_DIRECTORY
    "./image/Announcement/StartPlant.png", // START_PLANT_DIRECTORY
    "./image/Black_Screen.png",            // BLACK_SCREEN_DIRECTORY
    "./image/Announcement/NextWave.png",   // HUGE_WAVE_DIRECTORY

};

const int N_SHEET[] = {
    // Plant sheet
    0,  // PEASHOOTER_DIRECTORY
    60, // PEASHOOTER_SHEET_DIRECTORY
    60, // PEASHOOTER_SHEET_BLINK_DIRECTORY
    60, // PEASHOOTER_ATTACK_DIRECTORY
    60, // PEASHOOTER_ATTACK_BLINK_DIRECTORY

    0,  // SUNFLOWER_DIRECTORY
    60, // SUNFLOWER_SHEET_DIRECTORY
    60, // SUNFLOWER_SHEET_BLINK_DIRECTORY
    15, // SUNFLOWER_HAPPY_DIRECTORY
    15, // SUNFLOWER_HAPPY_BLINK_DIRECTORY

    0, // WALNUT_DIRECTORY
    3, // WALNUT_1_DIRECTORY
    2, // WALNUT_2_DIRECTORY
    2, // WALNUT_3_DIRECTORY
    2, // WALNUT_4_DIRECTORY
    3, // WALNUT_1_BLINK_DIRECTORY
    2, // WALNUT_2_BLINK_DIRECTORY
    2, // WALNUT_3_BLINK_DIRECTORY
    2, // WALNUT_4_BLINK_DIRECTORY

    0,  // SNOWPEA_DIRECTORY
    60, // SNOWPEA_SHEET_DIRECTORY
    60, // SNOWPEA_ATTACK_DIRECTORY

    0, // PEASHOOTER_ICON_BRIGHT_DIRECTORY
    0, // PEASHOOTER_ICON_DIM_DIRECTORY
    0, // SUNFLOWER_ICON_BRIGHT_DIRECTORY
    0, // SUNFLOWER_ICON_DIM_DIRECTORY
    0, // WALNUT_ICON_BRIGHT_DIRECTORY
    0, // WALNUT_ICON_DIM_DIRECTORY
    0, // SNOWPEA_ICON_BRIGHT_DIRECTORY
    0, // SNOWPEA_ICON_DIM_DIRECTORY

    0, // PEA_DIRECTORY
    0, // PEA_EXPLODE_DIRECTORY
    0, // SNOWZ_PEA_DIRECTORY
    0, // SNOWZ_PEA_EXPLODE_DIRECTORY

    0, // STARTING_SCREEN_DIRECTORY
    0, // CHOOSE_LEVELS_DIRECTORY
    0, // BACKGROUND_DIRECTORY
    0, // BACKGROUND_LV1_DIRECTORY
    0, // BACKGROUND_LV2_DIRECTORY
    0, // LOSING_MESSAGE_DIRECTORY
    0, // WINNING_MESSAGE_DIRECTORY

    0, // SUN_DIRECTORY
    0, // SUN_BAR_DIRECTORY
    0, // ICON_BAR_DIRECTORY
    0, // SHOVEL_BAR_DIRECTORY
    0, // SHOVEL_DIRECTORY
    0, // MENU_ICON_DIRECTORY
    0, // MENU_DIRECTORY
    0, // CONTINUE_DIRECTORY

    22, // ZOMBIE_WALK1_DIRECTORY
    31, // ZOMBIE_WALK2_DIRECTORY
    22, // ZOMBIE_WALK1_BLINK_DIRECTORY,
    31, // ZOMBIE_WALK2_BLINK_DIRECTORY
    10, // ZOMBIE_DIE_DIRECTORY
    12, // ZOMBIE_HEAD_DIRECTORY
    11, // ZOMBIE_EATING_DIRECTORY
    11, // ZOMBIE_EATING_BLINK_DIRECTORY

    21, // CONE_ZOMBIE_WALK_DIRECTORY
    21, // CONE_ZOMBIE_WALK_BLINK_DIRECTORY
    11, // CONE_ZOMBIE_EATING_DIRECTORY
    11, // CONE_ZOMBIE_EATING_BLINK_DIRECTORY

    15, // BUCKET_ZOMBIE_WALK_DIRECTORY
    15, // BUCKET_ZOMBIE_WALK_BLINK_DIRECTORY
    11, // BUCKET_ZOMBIE_EATING_DIRECTORY
    11, // BUCKET_ZOMBIE_EATING_BLINK_DIRECTORY

    0, // START_READY_DIRECTORY
    0, // START_SET_DIRECTORY
    0, // START_PLANT_DIRECTORY
    0, // BLACK_SCREEN_DIRECTORY
    0, // HUGE_WAVE_DIRECTORY

};

const int C_SHEET[] = {
    // Plant sheet
    0, // PEASHOOTER_DIRECTORY
    8, // PEASHOOTER_SHEET_DIRECTORY
    8, // PEASHOOTER_SHEET_BLINK_DIRECTORY
    8, // PEASHOOTER_ATTACK_DIRECTORY
    8, // PEASHOOTER_ATTACK_BLINK_DIRECTORY

    0, // SUNFLOWER_DIRECTORY
    8, // SUNFLOWER_SHEET_DIRECTORY
    8, // SUNFLOWER_SHEET_BLINK_DIRECTORY
    8, // SUNFLOWER_HAPPY_DIRECTORY
    8, // SUNFLOWER_HAPPY_BLINK_DIRECTORY

    0, // WALNUT_DIRECTORY
    3, // WALNUT_1_DIRECTORY
    2, // WALNUT_2_DIRECTORY
    2, // WALNUT_3_DIRECTORY
    2, // WALNUT_4_DIRECTORY
    3, // WALNUT_1_BLINK_DIRECTORY
    2, // WALNUT_2_BLINK_DIRECTORY
    2, // WALNUT_3_BLINK_DIRECTORY
    2, // WALNUT_4_BLINK_DIRECTORY

    0, // SNOWPEA_DIRECTORY
    8, // SNOWPEA_SHEET_DIRECTORY
    8, // SNOWPEA_ATTACK_DIRECTORY

    0, // PEASHOOTER_ICON_BRIGHT_DIRECTORY
    0, // PEASHOOTER_ICON_DIM_DIRECTORY
    0, // SUNFLOWER_ICON_BRIGHT_DIRECTORY
    0, // SUNFLOWER_ICON_DIM_DIRECTORY
    0, // WALNUT_ICON_BRIGHT_DIRECTORY
    0, // WALNUT_ICON_DIM_DIRECTORY
    0, // SNOWPEA_ICON_BRIGHT_DIRECTORY
    0, // SNOWPEA_ICON_DIM_DIRECTORY

    0, // PEA_DIRECTORY
    0, // PEA_EXPLODE_DIRECTORY
    0, // SNOWZ_PEA_DIRECTORY
    0, // SNOWZ_PEA_EXPLODE_DIRECTORY

    0, // STARTING_SCREEN_DIRECTORY
    0, // CHOOSE_LEVELS_DIRECTORY
    0, // BACKGROUND_DIRECTORY
    0, // BACKGROUND_LV1_DIRECTORY
    0, // BACKGROUND_LV2_DIRECTORY
    0, // LOSING_MESSAGE_DIRECTORY
    0, // WINNING_MESSAGE_DIRECTORY

    0, // SUN_DIRECTORY
    0, // SUN_BAR_DIRECTORY
    0, // ICON_BAR_DIRECTORY
    0, // SHOVEL_BAR_DIRECTORY
    0, // SHOVEL_DIRECTORY
    0, // MENU_ICON_DIRECTORY
    0, // MENU_DIRECTORY
    0, // CONTINUE_DIRECTORY

    8,  // ZOMBIE_WALK1_DIRECTORY
    8,  // ZOMBIE_WALK2_DIRECTORY
    8,  // ZOMBIE_WALK1_BLINK_DIRECTORY,
    8,  // ZOMBIE_WALK2_BLINK_DIRECTORY
    3,  // ZOMBIE_DIE_DIRECTORY
    12, // ZOMBIE_HEAD_DIRECTORY
    8,  // ZOMBIE_EATING_DIRECTORY
    8,  // ZOMBIE_EATING_BLINK_DIRECTORY

    8, // CONE_ZOMBIE_WALK_DIRECTORY
    8, // CONE_ZOMBIE_WALK_BLINK_DIRECTORY
    8, // CONE_ZOMBIE_EATING_DIRECTORY
    8, // CONE_ZOMBIE_EATING_BLINK_DIRECTORY

    8, // BUCKET_ZOMBIE_WALK_DIRECTORY
    8, // BUCKET_ZOMBIE_WALK_BLINK_DIRECTORY
    8, // BUCKET_ZOMBIE_EATING_DIRECTORY
    8, // BUCKET_ZOMBIE_EATING_BLINK_DIRECTORY

    0, // START_READY_DIRECTORY
    0, // START_SET_DIRECTORY
    0, // START_PLANT_DIRECTORY
    0, // BLACK_SCREEN_DIRECTORY
    0, // HUGE_WAVE_DIRECTORY

};
