#pragma once
#include <string>
#include <map>
using namespace std;

#define ZOMBIE_SHEET_DIRECTORY rand(ZOMBIE_WALK1_DIRECTORY, ZOMBIE_WALK2_DIRECTORY)

enum ImageType
{
    NULL_DIRECTORY = -1,

    // Plant seed
    PEASHOOTER_DIRECTORY,
    PEASHOOTER_SHEET_DIRECTORY,
    PEASHOOTER_SHEET_BLINK_DIRECTORY,
    PEASHOOTER_ATTACK_DIRECTORY,
    PEASHOOTER_ATTACK_BLINK_DIRECTORY,

    SUNFLOWER_DIRECTORY,
    SUNFLOWER_SHEET_DIRECTORY,
    SUNFLOWER_SHEET_BLINK_DIRECTORY,
    SUNFLOWER_HAPPY_DIRECTORY,
    SUNFLOWER_HAPPY_BLINK_DIRECTORY,

    WALNUT_DIRECTORY,
    WALNUT_1_DIRECTORY,
    WALNUT_2_DIRECTORY,
    WALNUT_3_DIRECTORY,
    WALNUT_4_DIRECTORY,
    WALNUT_1_BLINK_DIRECTORY,
    WALNUT_2_BLINK_DIRECTORY,
    WALNUT_3_BLINK_DIRECTORY,
    WALNUT_4_BLINK_DIRECTORY,

    SNOWPEA_DIRECTORY,
    SNOWPEA_SHEET_DIRECTORY,
    SNOWPEA_ATTACK_DIRECTORY,

    CHERRYBOMB_DIRECTORY,
    CHERRYBOMB_SHEET_DIRECTORY,

    PEASHOOTER_ICON_BRIGHT_DIRECTORY,
    PEASHOOTER_ICON_DIM_DIRECTORY,
    SUNFLOWER_ICON_BRIGHT_DIRECTORY,
    SUNFLOWER_ICON_DIM_DIRECTORY,
    WALNUT_ICON_BRIGHT_DIRECTORY,
    WALNUT_ICON_DIM_DIRECTORY,
    SNOWPEA_ICON_BRIGHT_DIRECTORY,
    SNOWPEA_ICON_DIM_DIRECTORY,
    CHERRYBOMB_ICON_BRIGHT_DIRECTORY,
    CHERRYBOMB_ICON_DIM_DIRECTORY,

    PEA_DIRECTORY,
    PEA_EXPLODE_DIRECTORY,
    SNOWZ_PEA_DIRECTORY,
    SNOWZ_PEA_EXPLODE_DIRECTORY,

    STARTING_SCREEN_DIRECTORY,
    CHOOSE_LEVELS_DIRECTORY,
    LEVEL_BLINK_DIRECTORY,
    BACKGROUND_LV1_DIRECTORY,
    BACKGROUND_LV2_DIRECTORY,
    BACKGROUND_DIRECTORY,
    BACKGROUND_NIGHT_DIRECTORY,
    LOSING_MESSAGE_DIRECTORY,
    WINNING_MESSAGE_DIRECTORY,

    SUN_DIRECTORY,
    SUN2_DIRECTORY,
    SUN_BAR_DIRECTORY,
    ICON_BAR_DIRECTORY,
    SHOVEL_BAR_DIRECTORY,
    SHOVEL_DIRECTORY,
    MENU_ICON_DIRECTORY,
    MENU_DIRECTORY,
    CONTINUE_DIRECTORY,
    RENAME_DIRECTORY,
    RESET_LEVEL_DIRECTORY,
    QUIT_DIRECTORY,
    OK_DIRECTORY,
    CANCEL_DIRECTORY,
    RENAME_MENU_DIRECTORY,
    NEW_USER_DIRECTORY,

    // NORMAL ZOMBIE---------------------------------------------------
    ZOMBIE_WALK1_DIRECTORY,
    ZOMBIE_WALK2_DIRECTORY,
    ZOMBIE_WALK3_DIRECTORY,

    ZOMBIE_WALK1_BLINK_DIRECTORY,
    ZOMBIE_WALK2_BLINK_DIRECTORY,
    ZOMBIE_WALK3_BLINK_DIRECTORY,

    ZOMBIE_WALK1_COLD_DIRECTORY,
    ZOMBIE_WALK2_COLD_DIRECTORY,
    ZOMBIE_WALK3_COLD_DIRECTORY,

    ZOMBIE_DIE_DIRECTORY,
    ZOMBIE_DIE_COLD_DIRECTORY,
    ZOMBIE_HEAD_DIRECTORY,
    ZOMBIE_HEAD_COLD_DIRECTORY,
    ZOMBIE_BURNT_DIRECTORY,

    ZOMBIE_EATING_DIRECTORY,
    ZOMBIE_EATING_BLINK_DIRECTORY,
    ZOMBIE_EATING_COLD_DIRECTORY,

    // FLAG ZOMBIE--------------------------------------------------------
    FLAG_ZOMBIE_WALK_DIRECTORY,
    FLAG_ZOMBIE_WALK_BLINK_DIRECTORY,
    FLAG_ZOMBIE_WALK_COLD_DIRECTORY,

    FLAG_ZOMBIE_EATING_DIRECTORY,
    FLAG_ZOMBIE_EATING_BLINK_DIRECTORY,
    FLAG_ZOMBIE_EATING_COLD_DIRECTORY,

    // CONEHEAD ZOMBIE--------------------------------------------------------
    CONE_DROP_DIRECTORY,

    CONE_ZOMBIE_WALK_1_DIRECTORY,
    CONE_ZOMBIE_WALK_2_DIRECTORY,
    CONE_ZOMBIE_WALK_3_DIRECTORY,

    CONE_ZOMBIE_WALK_1_BLINK_DIRECTORY,
    CONE_ZOMBIE_WALK_2_BLINK_DIRECTORY,
    CONE_ZOMBIE_WALK_3_BLINK_DIRECTORY,

    CONE_ZOMBIE_WALK_1_COLD_DIRECTORY,
    CONE_ZOMBIE_WALK_2_COLD_DIRECTORY,
    CONE_ZOMBIE_WALK_3_COLD_DIRECTORY,

    CONE_ZOMBIE_EATING_1_DIRECTORY,
    CONE_ZOMBIE_EATING_2_DIRECTORY,
    CONE_ZOMBIE_EATING_3_DIRECTORY,

    CONE_ZOMBIE_EATING_1_BLINK_DIRECTORY,
    CONE_ZOMBIE_EATING_2_BLINK_DIRECTORY,
    CONE_ZOMBIE_EATING_3_BLINK_DIRECTORY,

    CONE_ZOMBIE_EATING_1_COLD_DIRECTORY,
    CONE_ZOMBIE_EATING_2_COLD_DIRECTORY,
    CONE_ZOMBIE_EATING_3_COLD_DIRECTORY,

    // BUCKETHEAD ZOMBIE--------------------------------------------------------
    BUCKET_DROP_DIRECTORY,

    BUCKET_ZOMBIE_WALK_1_DIRECTORY,
    BUCKET_ZOMBIE_WALK_2_DIRECTORY,
    BUCKET_ZOMBIE_WALK_3_DIRECTORY,

    BUCKET_ZOMBIE_WALK_1_BLINK_DIRECTORY,
    BUCKET_ZOMBIE_WALK_2_BLINK_DIRECTORY,
    BUCKET_ZOMBIE_WALK_3_BLINK_DIRECTORY,

    BUCKET_ZOMBIE_WALK_1_COLD_DIRECTORY,
    BUCKET_ZOMBIE_WALK_2_COLD_DIRECTORY,
    BUCKET_ZOMBIE_WALK_3_COLD_DIRECTORY,

    BUCKET_ZOMBIE_EATING_1_DIRECTORY,
    BUCKET_ZOMBIE_EATING_2_DIRECTORY,
    BUCKET_ZOMBIE_EATING_3_DIRECTORY,

    BUCKET_ZOMBIE_EATING_1_BLINK_DIRECTORY,
    BUCKET_ZOMBIE_EATING_2_BLINK_DIRECTORY,
    BUCKET_ZOMBIE_EATING_3_BLINK_DIRECTORY,

    BUCKET_ZOMBIE_EATING_1_COLD_DIRECTORY,
    BUCKET_ZOMBIE_EATING_2_COLD_DIRECTORY,
    BUCKET_ZOMBIE_EATING_3_COLD_DIRECTORY,

    //-------------------------------------------------------
    START_READY_DIRECTORY,
    START_SET_DIRECTORY,
    START_PLANT_DIRECTORY,
    BLACK_SCREEN_DIRECTORY,
    HUGE_WAVE_DIRECTORY,
    FINAL_WAVE_DIRECTORY,

    COUNT_USED_DIRECTORY
};

const string image_directory[] = {
    // Plant sheet
    "./image/Plant_sheet/peashooter/Peashooter.png",              // PEASHOOTER_DIRECTORY
    "./image/Plant_sheet/peashooter/peashooter_sheet.png",        // PEASHOOTER_SHEET_DIRECTORY
    "./image/Plant_sheet/peashooter/peashooter_sheet_blink.png",  // PEASHOOTER_SHEET_BLINK_DIRECTORY
    "./image/Plant_sheet/peashooter/peashooter_attack.png",       // PEASHOOTER_ATTACK_DIRECTORY
    "./image/Plant_sheet/peashooter/peashooter_attack_blink.png", // PEASHOOTER_ATTACK_BLINK_DIRECTORY

    "./image/Plant_sheet/sunflower/Sunflower.png",             // SUNFLOWER_DIRECTORY
    "./image/Plant_sheet/sunflower/sunflower_sheet.png",       // SUNFLOWER_SHEET_DIRECTORY
    "./image/Plant_sheet/sunflower/sunflower_sheet_blink.png", // SUNFLOWER_SHEET_BLINK_DIRECTORY
    "./image/Plant_sheet/sunflower/sunflower_happy.png",       // SUNFLOWER_HAPPY_DIRECTORY
    "./image/Plant_sheet/sunflower/sunflower_happy_blink.png", // SUNFLOWER_HAPPY_BLINK_DIRECTORY

    "./image/Plant_sheet/walnut/Walnut.png",               // WALNUT_DIRECTORY
    "./image/Plant_sheet/walnut/Walnut-sheet-1.png",       // WALNUT_1_DIRECTORY
    "./image/Plant_sheet/walnut/Walnut-sheet-2.png",       // WALNUT_2_DIRECTORY
    "./image/Plant_sheet/walnut/Walnut-sheet-3.png",       // WALNUT_3_DIRECTORY
    "./image/Plant_sheet/walnut/Walnut-sheet-4.png",       // WALNUT_4_DIRECTORY
    "./image/Plant_sheet/walnut/Walnut-sheet-1_blink.png", // WALNUT_1_BLINK_DIRECTORY
    "./image/Plant_sheet/walnut/Walnut-sheet-2_blink.png", // WALNUT_2_BLINK_DIRECTORY
    "./image/Plant_sheet/walnut/Walnut-sheet-3_blink.png", // WALNUT_3_BLINK_DIRECTORY
    "./image/Plant_sheet/walnut/Walnut-sheet-4_blink.png", // WALNUT_4_BLINK_DIRECTORY

    "./image/Plant_sheet/snowpea/SnowPea.png",        // SNOWPEA_DIRECTORY
    "./image/Plant_sheet/snowpea/snowpea_sheet.png",  // SNOWPEA_SHEET_DIRECTORY
    "./image/Plant_sheet/snowpea/snowpea_attack.png", // SNOWPEA_ATTACK_DIRECTORY

    "./image/Plant_sheet/cherrybomb/Cherrybomb.png",       // CHERRYBOMB_DIRECTORY
    "./image/Plant_sheet/cherrybomb/cherrybomb_sheet.png", // CHERRYBOMB_SHEET_DIRECTORY

    "./image/Plant_seed/Peashooter_Seed_Packet.png",     // PEASHOOTER_ICON_BRIGHT_DIRECTORY
    "./image/Plant_seed/Peashooter_Seed_Packet_dim.png", // PEASHOOTER_ICON_DIM_DIRECTORY
    "./image/Plant_seed/Sunflower_Seed_Packet.png",      // SUNFLOWER_ICON_BRIGHT_DIRECTORY
    "./image/Plant_seed/Sunflower_Seed_Packet_dim.png",  // SUNFLOWER_ICON_DIM_DIRECTORY
    "./image/Plant_seed/Walnut_Seed_Packet.png",         // WALNUT_ICON_BRIGHT_DIRECTORY
    "./image/Plant_seed/Walnut_Seed_Packet_dim.png",     // WALNUT_ICON_DIM_DIRECTORY
    "./image/Plant_seed/Snowpea_Seed_Packet.png",        // SNOWPEA_ICON_BRIGHT_DIRECTORY
    "./image/Plant_seed/Snowpea_Seed_Packet_dim.png",    // SNOWPEA_ICON_DIM_DIRECTORY
    "./image/Plant_seed/Cherrybomb_Seed_Packet.png",     // CHERRYBOMB_ICON_BRIGHT_DIRECTORY
    "./image/Plant_seed/Cherrybomb_Seed_Packet_dim.png", // CHERRYBOMB_ICON_DIM_DIRECTORY

    "./image/Bullets/Pea/pea.png",                     // PEA_DIRECTORY
    "./image/Bullets/Pea/pea_explode.png",             // PEA_EXPLODE_DIRECTORY
    "./image/Bullets/Snowz_pea/snowz_pea.png",         // SNOWZ_PEA_DIRECTORY
    "./image/Bullets/Snowz_pea/snowz_pea_explode.png", // SNOWZ_PEA_EXPLODE_DIRECTORY

    "./image/Background/Starting_Screen.png", // STARTING_SCREEN_DIRECTORY
    "./image/Background/Choose_levels.png",   // CHOOSE_LEVELS_DIRECTORY
    "./image/Background/level_blink.png",     // LEVEL_BLINK_DIRECTORY
    "./image/Background/Frontyard_LV1.png",   // BACKGROUND_LV1_DIRECTORY
    "./image/Background/Frontyard_LV2.png",   // BACKGROUND_LV2_DIRECTORY
    "./image/Background/Frontyard.png",       // BACKGROUND_DIRECTORY
    "./image/Background/Frontyard_night.png", // BACKGROUND_NIGHT_DIRECTORY
    "./image/Background/ZombiesWon.png",      // LOSING_MESSAGE_DIRECTORY
    "./image/Background/Winning_Pic.png",     // WINNING_MESSAGE_DIRECTORY

    "./image/Icons/sun.png",         // SUN_DIRECTORY
    "./image/Icons/sun2.png",        // SUN2_DIRECTORY
    "./image/Icons/sun_bar.png",     // SUN_BAR_DIRECTORY
    "./image/Icons/Item_Bar.png",    // ICON_BAR_DIRECTORY
    "./image/Icons/Shovel.png",      // SHOVEL_BAR_DIRECTORY
    "./image/Icons/Shovel2.png",     // SHOVEL_DIRECTORY
    "./image/Icons/menu_icon.png",   // MENU_ICON_DIRECTORY
    "./image/Icons/menu.png",        // MENU_DIRECTORY
    "./image/Icons/continue.png",    // CONTINUE_DIRECTORY
    "./image/Icons/rename.png",      // RENAME_DIRECTORY
    "./image/Icons/reset_level.png", // RESET_LEVEL_DIRECTORY
    "./image/Icons/quit.png",        // QUIT_DIRECTORY
    "./image/Icons/ok.png",          // OK_DIRECTORY
    "./image/Icons/cancel.png",      // CANCEL_DIRECTORY
    "./image/Icons/rename_menu.png", // RENAME_MENU_DIRECTORY
    "./image/Icons/new_user.png",    // NEW_USER_DIRECTORY

    // NORMAL ZOMBIE------------------------------------------------------------------------
    "./image/Zombie/Normal/ZombieWalk1.png", // ZOMBIE_WALK1_DIRECTORY
    "./image/Zombie/Normal/ZombieWalk2.png", // ZOMBIE_WALK2_DIRECTORY
    "./image/Zombie/Normal/ZombieWalk3.png", // ZOMBIE_WALK3_DIRECTORY

    "./image/Zombie/Normal/ZombieWalk1_blink.png", // ZOMBIE_WALK1_BLINK_DIRECTORY
    "./image/Zombie/Normal/ZombieWalk2_blink.png", // ZOMBIE_WALK2_BLINK_DIRECTORY
    "./image/Zombie/Normal/ZombieWalk3_blink.png", // ZOMBIE_WALK3_BLINK_DIRECTORY

    "./image/Zombie/Normal/ZombieWalk1_cold.png", // ZOMBIE_WALK1_COLD_DIRECTORY
    "./image/Zombie/Normal/ZombieWalk2_cold.png", // ZOMBIE_WALK2_COLD_DIRECTORY
    "./image/Zombie/Normal/ZombieWalk3_cold.png", // ZOMBIE_WALK3_COLD_DIRECTORY

    "./image/Zombie/Normal/Zombie_die.png",       // ZOMBIE_DIE_DIRECTORY
    "./image/Zombie/Normal/Zombie_die_cold.png",  // ZOMBIE_DIE_COLD_DIRECTORY
    "./image/Zombie/Normal/Zombie_head.png",      // ZOMBIE_HEAD_DIRECTORY
    "./image/Zombie/Normal/Zombie_head_cold.png", // ZOMBIE_HEAD_COLD_DIRECTORY
    "./image/Zombie/Zombie_burnt.png",            // ZOMBIE_BURNT_DIRECTORY

    "./image/Zombie/Normal/ZombieAttack.png",       // ZOMBIE_EATING_DIRECTORY
    "./image/Zombie/Normal/ZombieAttack_blink.png", // ZOMBIE_EATING_BLINK_DIRECTORY
    "./image/Zombie/Normal/ZombieAttack_cold.png",  // ZOMBIE_EATING_COLD_DIRECTORY

    // FLAG ZOMBIE--------------------------------------------------------
    "./image/Zombie/Flag/FlagWalk.png",       // FLAG_ZOMBIE_WALK_DIRECTORY
    "./image/Zombie/Flag/FlagWalk_blink.png", // FLAG_ZOMBIE_WALK_BLINK_DIRECTORY
    "./image/Zombie/Flag/FlagWalk_cold.png",  // FLAG_ZOMBIE_WALK_COLD_DIRECTORY

    "./image/Zombie/Flag/FlagAttack.png",       // FLAG_ZOMBIE_EATING_DIRECTORY
    "./image/Zombie/Flag/FlagAttack_blink.png", // FLAG_ZOMBIE_EATING_BLINK_DIRECTORY
    "./image/Zombie/Flag/FlagAttack_cold.png",  // FLAG_ZOMBIE_EATING_COLD_DIRECTORY

    // CONEHEAD ZOMBIE------------------------------------------------------------------------
    "./image/Zombie/Cone/cone_drop.png", // CONE_DROP_DIRECTORY

    "./image/Zombie/Cone/ConeZombieWalk_1.png", // CONE_ZOMBIE_WALK_1_DIRECTORY
    "./image/Zombie/Cone/ConeZombieWalk_2.png", // CONE_ZOMBIE_WALK_2_DIRECTORY
    "./image/Zombie/Cone/ConeZombieWalk_3.png", // CONE_ZOMBIE_WALK_3_DIRECTORY

    "./image/Zombie/Cone/ConeZombieWalk_1_blink.png", // CONE_ZOMBIE_WALK_1_BLINK_DIRECTORY
    "./image/Zombie/Cone/ConeZombieWalk_2_blink.png", // CONE_ZOMBIE_WALK_2_BLINK_DIRECTORY
    "./image/Zombie/Cone/ConeZombieWalk_3_blink.png", // CONE_ZOMBIE_WALK_3_BLINK_DIRECTORY

    "./image/Zombie/Cone/ConeZombieWalk_1_cold.png", // CONE_ZOMBIE_WALK_1_COLD_DIRECTORY
    "./image/Zombie/Cone/ConeZombieWalk_2_cold.png", // CONE_ZOMBIE_WALK_2_COLD_DIRECTORY
    "./image/Zombie/Cone/ConeZombieWalk_3_cold.png", // CONE_ZOMBIE_WALK_3_COLD_DIRECTORY

    "./image/Zombie/Cone/ConeZombieAttack_1.png", // CONE_ZOMBIE_EATING_1_DIRECTORY
    "./image/Zombie/Cone/ConeZombieAttack_2.png", // CONE_ZOMBIE_EATING_2_DIRECTORY
    "./image/Zombie/Cone/ConeZombieAttack_3.png", // CONE_ZOMBIE_EATING_3_DIRECTORY

    "./image/Zombie/Cone/ConeZombieAttack_1_blink.png", // CONE_ZOMBIE_EATING_1_BLINK_DIRECTORY
    "./image/Zombie/Cone/ConeZombieAttack_2_blink.png", // CONE_ZOMBIE_EATING_2_BLINK_DIRECTORY
    "./image/Zombie/Cone/ConeZombieAttack_3_blink.png", // CONE_ZOMBIE_EATING_3_BLINK_DIRECTORY

    "./image/Zombie/Cone/ConeZombieAttack_1_cold.png", // CONE_ZOMBIE_EATING_1_COLD_DIRECTORY
    "./image/Zombie/Cone/ConeZombieAttack_2_cold.png", // CONE_ZOMBIE_EATING_2_COLD_DIRECTORY
    "./image/Zombie/Cone/ConeZombieAttack_3_cold.png", // CONE_ZOMBIE_EATING_3_COLD_DIRECTORY

    // BUCKETHEAD ZOMBIE------------------------------------------------------------------------
    "./image/Zombie/Bucket/bucket_drop.png", // BUCKET_DROP_DIRECTORY

    "./image/Zombie/Bucket/BucketZombieWalk_1.png", // BUCKET_ZOMBIE_WALK_1_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieWalk_2.png", // BUCKET_ZOMBIE_WALK_2_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieWalk_3.png", // BUCKET_ZOMBIE_WALK_3_DIRECTORY

    "./image/Zombie/Bucket/BucketZombieWalk_1_blink.png", // BUCKET_ZOMBIE_WALK_1_BLINK_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieWalk_2_blink.png", // BUCKET_ZOMBIE_WALK_2_BLINK_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieWalk_3_blink.png", // BUCKET_ZOMBIE_WALK_3_BLINK_DIRECTORY

    "./image/Zombie/Bucket/BucketZombieWalk_1_cold.png", // BUCKET_ZOMBIE_WALK_1_COLD_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieWalk_2_cold.png", // BUCKET_ZOMBIE_WALK_2_COLD_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieWalk_3_cold.png", // BUCKET_ZOMBIE_WALK_3_COLD_DIRECTORY

    "./image/Zombie/Bucket/BucketZombieAttack_1.png", // BUCKET_ZOMBIE_EATING_1_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieAttack_2.png", // BUCKET_ZOMBIE_EATING_2_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieAttack_3.png", // BUCKET_ZOMBIE_EATING_3_DIRECTORY

    "./image/Zombie/Bucket/BucketZombieAttack_1_blink.png", // BUCKET_ZOMBIE_EATING_1_BLINK_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieAttack_2_blink.png", // BUCKET_ZOMBIE_EATING_2_BLINK_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieAttack_3_blink.png", // BUCKET_ZOMBIE_EATING_3_BLINK_DIRECTORY

    "./image/Zombie/Bucket/BucketZombieAttack_1_cold.png", // BUCKET_ZOMBIE_EATING_1_COLD_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieAttack_2_cold.png", // BUCKET_ZOMBIE_EATING_2_COLD_DIRECTORY
    "./image/Zombie/Bucket/BucketZombieAttack_3_cold.png", // BUCKET_ZOMBIE_EATING_3_COLD_DIRECTORY

    //----------------------------------------------------------------------------------------------
    "./image/Announcement/StartReady.png", // START_READY_DIRECTORY
    "./image/Announcement/StartSet.png",   // START_SET_DIRECTORY
    "./image/Announcement/StartPlant.png", // START_PLANT_DIRECTORY
    "./image/Black_Screen.png",            // BLACK_SCREEN_DIRECTORY
    "./image/Announcement/NextWave.png",   // HUGE_WAVE_DIRECTORY
    "./image/Announcement/FinalWave.png",  // FINAL_WAVE_DIRECTORY

};

const int N_SHEET[] = {
    // Plant sheet
    0,  // PEASHOOTER_DIRECTORY
    60, // PEASHOOTER_SHEET_DIRECTORY
    60, // PEASHOOTER_SHEET_BLINK_DIRECTORY
    60, // PEASHOOTER_ATTACK_DIRECTORY
    60, // PEASHOOTER_ATTACK_BLINK_DIRECTORY

    0,  // SUNFLOWER_DIRECTORY
    60, // SUNFLOWER_SHEET_DIRECTORY
    60, // SUNFLOWER_SHEET_BLINK_DIRECTORY
    15, // SUNFLOWER_HAPPY_DIRECTORY
    15, // SUNFLOWER_HAPPY_BLINK_DIRECTORY

    0, // WALNUT_DIRECTORY
    3, // WALNUT_1_DIRECTORY
    2, // WALNUT_2_DIRECTORY
    2, // WALNUT_3_DIRECTORY
    2, // WALNUT_4_DIRECTORY
    3, // WALNUT_1_BLINK_DIRECTORY
    2, // WALNUT_2_BLINK_DIRECTORY
    2, // WALNUT_3_BLINK_DIRECTORY
    2, // WALNUT_4_BLINK_DIRECTORY

    0,  // SNOWPEA_DIRECTORY
    60, // SNOWPEA_SHEET_DIRECTORY
    60, // SNOWPEA_ATTACK_DIRECTORY

    0,  // CHERRYBOMB_DIRECTORY
    24, // CHERRYBOMB_SHEET_DIRECTORY

    0, // PEASHOOTER_ICON_BRIGHT_DIRECTORY
    0, // PEASHOOTER_ICON_DIM_DIRECTORY
    0, // SUNFLOWER_ICON_BRIGHT_DIRECTORY
    0, // SUNFLOWER_ICON_DIM_DIRECTORY
    0, // WALNUT_ICON_BRIGHT_DIRECTORY
    0, // WALNUT_ICON_DIM_DIRECTORY
    0, // SNOWPEA_ICON_BRIGHT_DIRECTORY
    0, // SNOWPEA_ICON_DIM_DIRECTORY
    0, // CHERRYBOMB_ICON_BRIGHT_DIRECTORY
    0, // CHERRYBOMB_ICON_DIM_DIRECTORY

    0, // PEA_DIRECTORY
    0, // PEA_EXPLODE_DIRECTORY
    0, // SNOWZ_PEA_DIRECTORY
    0, // SNOWZ_PEA_EXPLODE_DIRECTORY

    0, // STARTING_SCREEN_DIRECTORY
    0, // CHOOSE_LEVELS_DIRECTORY
    0, // LEVEL_BLINK_DIRECTORY
    0, // BACKGROUND_LV1_DIRECTORY
    0, // BACKGROUND_LV2_DIRECTORY
    0, // BACKGROUND_DIRECTORY
    0, // BACKGROUND_NIGHT_DIRECTORY
    0, // LOSING_MESSAGE_DIRECTORY
    0, // WINNING_MESSAGE_DIRECTORY

    0, // SUN_DIRECTORY
    0, // SUN2_DIRECTORY
    0, // SUN_BAR_DIRECTORY
    0, // ICON_BAR_DIRECTORY
    0, // SHOVEL_BAR_DIRECTORY
    0, // SHOVEL_DIRECTORY
    0, // MENU_ICON_DIRECTORY
    0, // MENU_DIRECTORY
    0, // CONTINUE_DIRECTORY
    0, // RENAME_DIRECTORY
    0, // RESET_LEVEL_DIRECTORY
    0, // QUIT_DIRECTORY
    0, // OK_DIRECTORY
    0, // CANCEL_DIRECTORY
    0, // RENAME_MENU_DIRECTORY
    0, // NEW_USER_DIRECTORY

    // NORMAL ZOMBIE----------------------------------------------------
    22, // ZOMBIE_WALK1_DIRECTORY
    31, // ZOMBIE_WALK2_DIRECTORY
    50, // ZOMBIE_WALK3_DIRECTORY

    22, // ZOMBIE_WALK1_BLINK_DIRECTORY
    31, // ZOMBIE_WALK2_BLINK_DIRECTORY
    50, // ZOMBIE_WALK3_BLINK_DIRECTORY

    22, // ZOMBIE_WALK1_COLD_DIRECTORY
    31, // ZOMBIE_WALK2_COLD_DIRECTORY
    50, // ZOMBIE_WALK3_COLD_DIRECTORY

    10, // ZOMBIE_DIE_DIRECTORY
    10, // ZOMBIE_DIE_COLD_DIRECTORY
    12, // ZOMBIE_HEAD_DIRECTORY
    12, // ZOMBIE_HEAD_COLD_DIRECTORY
    20, // ZOMBIE_BURNT_DIRECTORY

    11, // ZOMBIE_EATING_DIRECTORY
    11, // ZOMBIE_EATING_BLINK_DIRECTORY
    11, // ZOMBIE_EATING_COLD_DIRECTORY

    // FLAG ZOMBIE--------------------------------------------------------
    12, // FLAG_ZOMBIE_WALK_DIRECTORY
    12, // FLAG_ZOMBIE_WALK_BLINK_DIRECTORY
    12, // FLAG_ZOMBIE_WALK_COLD_DIRECTORY

    11, // FLAG_ZOMBIE_EATING_DIRECTORY
    11, // FLAG_ZOMBIE_EATING_BLINK_DIRECTORY
    11, // FLAG_ZOMBIE_EATING_COLD_DIRECTORY

    // CONEHEAD ZOMBIE-------------------------------------------------
    12, // CONE_DROP_DIRECTORY

    21, // CONE_ZOMBIE_WALK_1_DIRECTORY
    21, // CONE_ZOMBIE_WALK_2_DIRECTORY
    21, // CONE_ZOMBIE_WALK_3_DIRECTORY

    21, // CONE_ZOMBIE_WALK_1_BLINK_DIRECTORY
    21, // CONE_ZOMBIE_WALK_2_BLINK_DIRECTORY
    21, // CONE_ZOMBIE_WALK_3_BLINK_DIRECTORY

    21, // CONE_ZOMBIE_WALK_1_COLD_DIRECTORY
    21, // CONE_ZOMBIE_WALK_2_COLD_DIRECTORY
    21, // CONE_ZOMBIE_WALK_3_COLD_DIRECTORY

    11, // CONE_ZOMBIE_EATING_1_DIRECTORY
    11, // CONE_ZOMBIE_EATING_2_DIRECTORY
    11, // CONE_ZOMBIE_EATING_3_DIRECTORY

    11, // CONE_ZOMBIE_EATING_1_BLINK_DIRECTORY
    11, // CONE_ZOMBIE_EATING_2_BLINK_DIRECTORY
    11, // CONE_ZOMBIE_EATING_3_BLINK_DIRECTORY

    11, // CONE_ZOMBIE_EATING_1_COLD_DIRECTORY
    11, // CONE_ZOMBIE_EATING_2_COLD_DIRECTORY
    11, // CONE_ZOMBIE_EATING_3_COLD_DIRECTORY

    // BUCKETHEAD ZOMBIE-------------------------------------------------
    12, // BUCKET_DROP_DIRECTORY

    15, // BUCKET_ZOMBIE_WALK_1_DIRECTORY
    15, // BUCKET_ZOMBIE_WALK_2_DIRECTORY
    15, // BUCKET_ZOMBIE_WALK_3_DIRECTORY

    15, // BUCKET_ZOMBIE_WALK_1_BLINK_DIRECTORY
    15, // BUCKET_ZOMBIE_WALK_2_BLINK_DIRECTORY
    15, // BUCKET_ZOMBIE_WALK_3_BLINK_DIRECTORY

    15, // BUCKET_ZOMBIE_WALK_1_COLD_DIRECTORY
    15, // BUCKET_ZOMBIE_WALK_2_COLD_DIRECTORY
    15, // BUCKET_ZOMBIE_WALK_3_COLD_DIRECTORY

    11, // BUCKET_ZOMBIE_EATING_1_DIRECTORY
    11, // BUCKET_ZOMBIE_EATING_2_DIRECTORY
    11, // BUCKET_ZOMBIE_EATING_3_DIRECTORY

    11, // BUCKET_ZOMBIE_EATING_1_BLINK_DIRECTORY
    11, // BUCKET_ZOMBIE_EATING_2_BLINK_DIRECTORY
    11, // BUCKET_ZOMBIE_EATING_3_BLINK_DIRECTORY

    11, // BUCKET_ZOMBIE_EATING_1_COLD_DIRECTORY
    11, // BUCKET_ZOMBIE_EATING_2_COLD_DIRECTORY
    11, // BUCKET_ZOMBIE_EATING_3_COLD_DIRECTORY

    //--------------------------------------------------------------------
    0, // START_READY_DIRECTORY
    0, // START_SET_DIRECTORY
    0, // START_PLANT_DIRECTORY
    0, // BLACK_SCREEN_DIRECTORY
    0, // HUGE_WAVE_DIRECTORY
    0, // FINAL_WAVE_DIRECTORY

};

const int C_SHEET[] = {
    // Plant sheet
    0, // PEASHOOTER_DIRECTORY
    8, // PEASHOOTER_SHEET_DIRECTORY
    8, // PEASHOOTER_SHEET_BLINK_DIRECTORY
    8, // PEASHOOTER_ATTACK_DIRECTORY
    8, // PEASHOOTER_ATTACK_BLINK_DIRECTORY

    0, // SUNFLOWER_DIRECTORY
    8, // SUNFLOWER_SHEET_DIRECTORY
    8, // SUNFLOWER_SHEET_BLINK_DIRECTORY
    8, // SUNFLOWER_HAPPY_DIRECTORY
    8, // SUNFLOWER_HAPPY_BLINK_DIRECTORY

    0, // WALNUT_DIRECTORY
    3, // WALNUT_1_DIRECTORY
    2, // WALNUT_2_DIRECTORY
    2, // WALNUT_3_DIRECTORY
    2, // WALNUT_4_DIRECTORY
    3, // WALNUT_1_BLINK_DIRECTORY
    2, // WALNUT_2_BLINK_DIRECTORY
    2, // WALNUT_3_BLINK_DIRECTORY
    2, // WALNUT_4_BLINK_DIRECTORY

    0, // SNOWPEA_DIRECTORY
    8, // SNOWPEA_SHEET_DIRECTORY
    8, // SNOWPEA_ATTACK_DIRECTORY

    0, // CHERRYBOMB_DIRECTORY
    8, // CHERRYBOMB_SHEET_DIRECTORY

    0, // PEASHOOTER_ICON_BRIGHT_DIRECTORY
    0, // PEASHOOTER_ICON_DIM_DIRECTORY
    0, // SUNFLOWER_ICON_BRIGHT_DIRECTORY
    0, // SUNFLOWER_ICON_DIM_DIRECTORY
    0, // WALNUT_ICON_BRIGHT_DIRECTORY
    0, // WALNUT_ICON_DIM_DIRECTORY
    0, // SNOWPEA_ICON_BRIGHT_DIRECTORY
    0, // SNOWPEA_ICON_DIM_DIRECTORY
    0, // CHERRYBOMB_ICON_BRIGHT_DIRECTORY
    0, // CHERRYBOMB_ICON_DIM_DIRECTORY

    0, // PEA_DIRECTORY
    0, // PEA_EXPLODE_DIRECTORY
    0, // SNOWZ_PEA_DIRECTORY
    0, // SNOWZ_PEA_EXPLODE_DIRECTORY

    0, // STARTING_SCREEN_DIRECTORY
    0, // CHOOSE_LEVELS_DIRECTORY
    0, // LEVEL_BLINK_DIRECTORY
    0, // BACKGROUND_LV1_DIRECTORY
    0, // BACKGROUND_LV2_DIRECTORY
    0, // BACKGROUND_DIRECTORY
    0, // BACKGROUND_NIGHT_DIRECTORY
    0, // LOSING_MESSAGE_DIRECTORY
    0, // WINNING_MESSAGE_DIRECTORY

    0, // SUN_DIRECTORY
    0, // SUN2_DIRECTORY
    0, // SUN_BAR_DIRECTORY
    0, // ICON_BAR_DIRECTORY
    0, // SHOVEL_BAR_DIRECTORY
    0, // SHOVEL_DIRECTORY
    0, // MENU_ICON_DIRECTORY
    0, // MENU_DIRECTORY
    0, // CONTINUE_DIRECTORY
    0, // RENAME_DIRECTORY
    0, // RESET_LEVEL_DIRECTORY
    0, // QUIT_DIRECTORY
    0, // OK_DIRECTORY
    0, // CANCEL_DIRECTORY
    0, // RENAME_MENU_DIRECTORY
    0, // NEW_USER_DIRECTORY

    // NORMAL ZOMBIE------------------------------------------------------------
    8, // ZOMBIE_WALK1_DIRECTORY
    8, // ZOMBIE_WALK2_DIRECTORY
    8, // ZOMBIE_WALK3_DIRECTORY

    8, // ZOMBIE_WALK1_BLINK_DIRECTORY
    8, // ZOMBIE_WALK2_BLINK_DIRECTORY
    8, // ZOMBIE_WALK3_BLINK_DIRECTORY

    8, // ZOMBIE_WALK1_COLD_DIRECTORY
    8, // ZOMBIE_WALK2_COLD_DIRECTORY
    8, // ZOMBIE_WALK3_COLD_DIRECTORY

    3,  // ZOMBIE_DIE_DIRECTORY
    3,  // ZOMBIE_DIE_COLD_DIRECTORY
    12, // ZOMBIE_HEAD_DIRECTORY
    12, // ZOMBIE_HEAD_COLD_DIRECTORY
    8,  // ZOMBIE_BURNT_DIRECTORY

    8, // ZOMBIE_EATING_DIRECTORY
    8, // ZOMBIE_EATING_BLINK_DIRECTORY
    8, // ZOMBIE_EATING_COLD_DIRECTORY

    // FLAG ZOMBIE--------------------------------------------------------
    8, // FLAG_ZOMBIE_WALK_DIRECTORY
    8, // FLAG_ZOMBIE_WALK_BLINK_DIRECTORY
    8, // FLAG_ZOMBIE_WALK_COLD_DIRECTORY

    8, // FLAG_ZOMBIE_EATING_DIRECTORY
    8, // FLAG_ZOMBIE_EATING_BLINK_DIRECTORY
    8, // FLAG_ZOMBIE_EATING_COLD_DIRECTORY

    // CONEHEAD ZOMBIE------------------------------------------------------------
    12, // CONE_DROP_DIRECTORY

    8, // CONE_ZOMBIE_WALK_1_DIRECTORY
    8, // CONE_ZOMBIE_WALK_2_DIRECTORY
    8, // CONE_ZOMBIE_WALK_3_DIRECTORY

    8, // CONE_ZOMBIE_WALK_1_BLINK_DIRECTORY
    8, // CONE_ZOMBIE_WALK_2_BLINK_DIRECTORY
    8, // CONE_ZOMBIE_WALK_3_BLINK_DIRECTORY

    8, // CONE_ZOMBIE_WALK_1_COLD_DIRECTORY
    8, // CONE_ZOMBIE_WALK_2_COLD_DIRECTORY
    8, // CONE_ZOMBIE_WALK_3_COLD_DIRECTORY

    8, // CONE_ZOMBIE_EATING_1_DIRECTORY
    8, // CONE_ZOMBIE_EATING_2_DIRECTORY
    8, // CONE_ZOMBIE_EATING_3_DIRECTORY

    8, // CONE_ZOMBIE_EATING_1_BLINK_DIRECTORY
    8, // CONE_ZOMBIE_EATING_2_BLINK_DIRECTORY
    8, // CONE_ZOMBIE_EATING_3_BLINK_DIRECTORY

    8, // CONE_ZOMBIE_EATING_1_COLD_DIRECTORY
    8, // CONE_ZOMBIE_EATING_2_COLD_DIRECTORY
    8, // CONE_ZOMBIE_EATING_3_COLD_DIRECTORY

    // BUCKETHEAD ZOMBIE------------------------------------------------------------
    12, // BUCKET_DROP_DIRECTORY

    8, // BUCKET_ZOMBIE_WALK_1_DIRECTORY
    8, // BUCKET_ZOMBIE_WALK_2_DIRECTORY
    8, // BUCKET_ZOMBIE_WALK_3_DIRECTORY

    8, // BUCKET_ZOMBIE_WALK_1_BLINK_DIRECTORY
    8, // BUCKET_ZOMBIE_WALK_2_BLINK_DIRECTORY
    8, // BUCKET_ZOMBIE_WALK_3_BLINK_DIRECTORY

    8, // BUCKET_ZOMBIE_WALK_1_COLD_DIRECTORY
    8, // BUCKET_ZOMBIE_WALK_2_COLD_DIRECTORY
    8, // BUCKET_ZOMBIE_WALK_3_COLD_DIRECTORY

    8, // BUCKET_ZOMBIE_EATING_1_DIRECTORY
    8, // BUCKET_ZOMBIE_EATING_2_DIRECTORY
    8, // BUCKET_ZOMBIE_EATING_3_DIRECTORY

    8, // BUCKET_ZOMBIE_EATING_1_BLINK_DIRECTORY
    8, // BUCKET_ZOMBIE_EATING_2_BLINK_DIRECTORY
    8, // BUCKET_ZOMBIE_EATING_3_BLINK_DIRECTORY

    8, // BUCKET_ZOMBIE_EATING_1_COLD_DIRECTORY
    8, // BUCKET_ZOMBIE_EATING_2_COLD_DIRECTORY
    8, // BUCKET_ZOMBIE_EATING_3_COLD_DIRECTORY

    //-------------------------------------------------------------------------
    0, // START_READY_DIRECTORY
    0, // START_SET_DIRECTORY
    0, // START_PLANT_DIRECTORY
    0, // BLACK_SCREEN_DIRECTORY
    0, // HUGE_WAVE_DIRECTORY
    0, // FINAL_WAVE_DIRECTORY

};

static map<int, int> blink_of = {
    {PEASHOOTER_SHEET_DIRECTORY, PEASHOOTER_SHEET_BLINK_DIRECTORY},
    {PEASHOOTER_ATTACK_DIRECTORY, PEASHOOTER_ATTACK_BLINK_DIRECTORY},

    {SUNFLOWER_SHEET_DIRECTORY, SUNFLOWER_SHEET_BLINK_DIRECTORY},
    {SUNFLOWER_HAPPY_DIRECTORY, SUNFLOWER_HAPPY_BLINK_DIRECTORY},

    {WALNUT_1_DIRECTORY, WALNUT_1_BLINK_DIRECTORY},
    {WALNUT_2_DIRECTORY, WALNUT_2_BLINK_DIRECTORY},
    {WALNUT_3_DIRECTORY, WALNUT_3_BLINK_DIRECTORY},
    {WALNUT_4_DIRECTORY, WALNUT_4_BLINK_DIRECTORY},

    {SNOWPEA_SHEET_DIRECTORY, PEASHOOTER_SHEET_BLINK_DIRECTORY},
    {SNOWPEA_ATTACK_DIRECTORY, PEASHOOTER_ATTACK_BLINK_DIRECTORY},

    {ZOMBIE_WALK1_DIRECTORY, ZOMBIE_WALK1_BLINK_DIRECTORY},
    {ZOMBIE_WALK2_DIRECTORY, ZOMBIE_WALK2_BLINK_DIRECTORY},
    {ZOMBIE_WALK3_DIRECTORY, ZOMBIE_WALK3_BLINK_DIRECTORY},
    {ZOMBIE_EATING_DIRECTORY, ZOMBIE_EATING_BLINK_DIRECTORY},

    {FLAG_ZOMBIE_WALK_DIRECTORY, FLAG_ZOMBIE_WALK_BLINK_DIRECTORY},
    {FLAG_ZOMBIE_EATING_DIRECTORY, FLAG_ZOMBIE_EATING_BLINK_DIRECTORY},

    {CONE_ZOMBIE_WALK_1_DIRECTORY, CONE_ZOMBIE_WALK_1_BLINK_DIRECTORY},
    {CONE_ZOMBIE_WALK_2_DIRECTORY, CONE_ZOMBIE_WALK_2_BLINK_DIRECTORY},
    {CONE_ZOMBIE_WALK_3_DIRECTORY, CONE_ZOMBIE_WALK_3_BLINK_DIRECTORY},
    {CONE_ZOMBIE_EATING_1_DIRECTORY, CONE_ZOMBIE_EATING_1_BLINK_DIRECTORY},
    {CONE_ZOMBIE_EATING_2_DIRECTORY, CONE_ZOMBIE_EATING_2_BLINK_DIRECTORY},
    {CONE_ZOMBIE_EATING_3_DIRECTORY, CONE_ZOMBIE_EATING_3_BLINK_DIRECTORY},

    {BUCKET_ZOMBIE_WALK_1_DIRECTORY, BUCKET_ZOMBIE_WALK_1_BLINK_DIRECTORY},
    {BUCKET_ZOMBIE_WALK_2_DIRECTORY, BUCKET_ZOMBIE_WALK_2_BLINK_DIRECTORY},
    {BUCKET_ZOMBIE_WALK_3_DIRECTORY, BUCKET_ZOMBIE_WALK_3_BLINK_DIRECTORY},
    {BUCKET_ZOMBIE_EATING_1_DIRECTORY, BUCKET_ZOMBIE_EATING_1_BLINK_DIRECTORY},
    {BUCKET_ZOMBIE_EATING_2_DIRECTORY, BUCKET_ZOMBIE_EATING_2_BLINK_DIRECTORY},
    {BUCKET_ZOMBIE_EATING_3_DIRECTORY, BUCKET_ZOMBIE_EATING_3_BLINK_DIRECTORY}

};

static map<int, int> cold_of = {

    {ZOMBIE_WALK1_DIRECTORY, ZOMBIE_WALK1_COLD_DIRECTORY},
    {ZOMBIE_WALK2_DIRECTORY, ZOMBIE_WALK2_COLD_DIRECTORY},
    {ZOMBIE_WALK3_DIRECTORY, ZOMBIE_WALK3_COLD_DIRECTORY},
    {ZOMBIE_EATING_DIRECTORY, ZOMBIE_EATING_COLD_DIRECTORY},

    {FLAG_ZOMBIE_WALK_DIRECTORY, FLAG_ZOMBIE_WALK_COLD_DIRECTORY},
    {FLAG_ZOMBIE_EATING_DIRECTORY, FLAG_ZOMBIE_EATING_COLD_DIRECTORY},

    {ZOMBIE_HEAD_DIRECTORY, ZOMBIE_HEAD_COLD_DIRECTORY},
    {ZOMBIE_DIE_DIRECTORY, ZOMBIE_DIE_COLD_DIRECTORY},

    {CONE_ZOMBIE_WALK_1_DIRECTORY, CONE_ZOMBIE_WALK_1_COLD_DIRECTORY},
    {CONE_ZOMBIE_WALK_2_DIRECTORY, CONE_ZOMBIE_WALK_2_COLD_DIRECTORY},
    {CONE_ZOMBIE_WALK_3_DIRECTORY, CONE_ZOMBIE_WALK_3_COLD_DIRECTORY},
    {CONE_ZOMBIE_EATING_1_DIRECTORY, CONE_ZOMBIE_EATING_1_COLD_DIRECTORY},
    {CONE_ZOMBIE_EATING_2_DIRECTORY, CONE_ZOMBIE_EATING_2_COLD_DIRECTORY},
    {CONE_ZOMBIE_EATING_3_DIRECTORY, CONE_ZOMBIE_EATING_3_COLD_DIRECTORY},

    {BUCKET_ZOMBIE_WALK_1_DIRECTORY, BUCKET_ZOMBIE_WALK_1_COLD_DIRECTORY},
    {BUCKET_ZOMBIE_WALK_2_DIRECTORY, BUCKET_ZOMBIE_WALK_2_COLD_DIRECTORY},
    {BUCKET_ZOMBIE_WALK_3_DIRECTORY, BUCKET_ZOMBIE_WALK_3_COLD_DIRECTORY},
    {BUCKET_ZOMBIE_EATING_1_DIRECTORY, BUCKET_ZOMBIE_EATING_1_COLD_DIRECTORY},
    {BUCKET_ZOMBIE_EATING_2_DIRECTORY, BUCKET_ZOMBIE_EATING_2_COLD_DIRECTORY},
    {BUCKET_ZOMBIE_EATING_3_DIRECTORY, BUCKET_ZOMBIE_EATING_3_COLD_DIRECTORY}

};

static map<int, int> eat_of = {

    {ZOMBIE_WALK1_DIRECTORY, ZOMBIE_EATING_DIRECTORY},
    {ZOMBIE_WALK2_DIRECTORY, ZOMBIE_EATING_DIRECTORY},
    {ZOMBIE_WALK3_DIRECTORY, ZOMBIE_EATING_DIRECTORY},

    {FLAG_ZOMBIE_WALK_DIRECTORY, FLAG_ZOMBIE_EATING_DIRECTORY},

    {CONE_ZOMBIE_WALK_1_DIRECTORY, CONE_ZOMBIE_EATING_1_DIRECTORY},
    {CONE_ZOMBIE_WALK_2_DIRECTORY, CONE_ZOMBIE_EATING_2_DIRECTORY},
    {CONE_ZOMBIE_WALK_3_DIRECTORY, CONE_ZOMBIE_EATING_3_DIRECTORY},

    {BUCKET_ZOMBIE_WALK_1_DIRECTORY, BUCKET_ZOMBIE_EATING_1_DIRECTORY},
    {BUCKET_ZOMBIE_WALK_2_DIRECTORY, BUCKET_ZOMBIE_EATING_2_DIRECTORY},
    {BUCKET_ZOMBIE_WALK_3_DIRECTORY, BUCKET_ZOMBIE_EATING_3_DIRECTORY}

};

static map<int, int> walk_of = {

    {ZOMBIE_WALK1_DIRECTORY, ZOMBIE_EATING_DIRECTORY},
    {ZOMBIE_WALK2_DIRECTORY, ZOMBIE_EATING_DIRECTORY},
    {ZOMBIE_WALK3_DIRECTORY, ZOMBIE_EATING_DIRECTORY},

    {FLAG_ZOMBIE_EATING_DIRECTORY, FLAG_ZOMBIE_WALK_DIRECTORY},

    {CONE_ZOMBIE_EATING_1_DIRECTORY, CONE_ZOMBIE_WALK_1_DIRECTORY},
    {CONE_ZOMBIE_EATING_2_DIRECTORY, CONE_ZOMBIE_WALK_2_DIRECTORY},
    {CONE_ZOMBIE_EATING_3_DIRECTORY, CONE_ZOMBIE_WALK_3_DIRECTORY},

    {BUCKET_ZOMBIE_EATING_1_DIRECTORY, BUCKET_ZOMBIE_WALK_1_DIRECTORY},
    {BUCKET_ZOMBIE_EATING_2_DIRECTORY, BUCKET_ZOMBIE_WALK_2_DIRECTORY},
    {BUCKET_ZOMBIE_EATING_3_DIRECTORY, BUCKET_ZOMBIE_WALK_3_DIRECTORY}

};
