#pragma once
#include "support.hpp"
#include <map>
#include <string>
using namespace std;

#define ZOMBIE_CREDIT_DIRECTORY rand(ZOMBIE_CREDIT1_DIRECTORY, ZOMBIE_CREDIT2_DIRECTORY)
#define ZOMBIE_WALK_DIRECTORY rand(ZOMBIE_WALK1_DIRECTORY, ZOMBIE_WALK2_DIRECTORY)
#define ARMLESS_ZOMBIE_WALK_DIRECTORY rand(ARMLESS_ZOMBIE_WALK1_DIRECTORY, ARMLESS_ZOMBIE_WALK2_DIRECTORY)
#define ZOMBIE_DIE_DIRECTORY rand(ZOMBIE_DIE1_DIRECTORY, ZOMBIE_DIE2_DIRECTORY)

#define FLAG_ZOMBIE_WALK_1_DIRECTORY rand(FLAG_ZOMBIE_WALK1_1_DIRECTORY, FLAG_ZOMBIE_WALK2_1_DIRECTORY)
#define FLAG_ZOMBIE_WALK_2_DIRECTORY rand(FLAG_ZOMBIE_WALK1_2_DIRECTORY, FLAG_ZOMBIE_WALK2_2_DIRECTORY)
#define FLAG_ZOMBIE_WALK_3_DIRECTORY rand(FLAG_ZOMBIE_WALK1_3_DIRECTORY, FLAG_ZOMBIE_WALK2_3_DIRECTORY)

#define DOOR_ZOMBIE_WALK_1_DIRECTORY rand(DOOR_ZOMBIE_WALK1_1_DIRECTORY, DOOR_ZOMBIE_WALK2_1_DIRECTORY)
#define DOOR_ZOMBIE_WALK_2_DIRECTORY rand(DOOR_ZOMBIE_WALK1_2_DIRECTORY, DOOR_ZOMBIE_WALK2_2_DIRECTORY)
#define DOOR_ZOMBIE_WALK_3_DIRECTORY rand(DOOR_ZOMBIE_WALK1_3_DIRECTORY, DOOR_ZOMBIE_WALK2_3_DIRECTORY)

/*
Contain all image used for SDL
*/
enum ImageType
{
    NULL_DIRECTORY = -1,

    POPCAP_LOGO_DIRECTORY,
    EA_LOGO_DIRECTORY,

    PEASHOOTER_DIRECTORY,
    SUNFLOWER_DIRECTORY,
    WALLNUT_DIRECTORY,
    SNOWPEA_DIRECTORY,
    POTATOMINE_DIRECTORY,
    CHERRYBOMB_DIRECTORY,

    PEASHOOTER_SHEET_DIRECTORY,
    PEASHOOTER_SHEET_BLINK_DIRECTORY,
    PEASHOOTER_ATTACK_DIRECTORY,
    PEASHOOTER_ATTACK_BLINK_DIRECTORY,

    SUNFLOWER_SHEET_DIRECTORY,
    SUNFLOWER_SHEET_BLINK_DIRECTORY,
    SUNFLOWER_HAPPY_DIRECTORY,
    SUNFLOWER_HAPPY_BLINK_DIRECTORY,

    WALLNUT_1_DIRECTORY,
    WALLNUT_2_DIRECTORY,
    WALLNUT_3_DIRECTORY,
    WALLNUT_4_DIRECTORY,
    WALLNUT_5_DIRECTORY,
    WALLNUT_1_BLINK_DIRECTORY,
    WALLNUT_2_BLINK_DIRECTORY,
    WALLNUT_3_BLINK_DIRECTORY,
    WALLNUT_4_BLINK_DIRECTORY,
    WALLNUT_5_BLINK_DIRECTORY,

    SNOWPEA_SHEET_DIRECTORY,
    SNOWPEA_SHEET_BLINK_DIRECTORY,
    SNOWPEA_ATTACK_DIRECTORY,
    SNOWPEA_ATTACK_BLINK_DIRECTORY,

    CHERRYBOMB_SHEET_DIRECTORY,
    CHERRYBOMB_SHEET_BLINK_DIRECTORY,
    CHERRYBOMB_EXPLOSION_DIRECTORY,

    POTATOMINE_UNARMED_DIRECTORY,
    POTATOMINE_UNARMED_BLINK_DIRECTORY,
    POTATOMINE_RECOVER_DIRECTORY,
    POTATOMINE_RECOVER_BLINK_DIRECTORY,
    POTATOMINE_IDLE_DIRECTORY,
    POTATOMINE_ATTACK_DIRECTORY,
    POTATOMINE_EXPLOSION_DIRECTORY,

    SEED_CHOSEN_DIRECTORY,
    SEED_PACKET_DIRECTORY,
    SUN_TAG_DIRECTORY,
    SEED_PACKET_BOT_BORDER_DIRECTORY,

    SUNFLOWER_TROPHY_DIRECTORY,
    AWARD_SCREEN_DIRECTORY,

    PEA_DIRECTORY,
    PEA_EXPLODE_DIRECTORY,
    SNOWZ_PEA_DIRECTORY,
    SNOWZ_PEA_EXPLODE_DIRECTORY,

    STARTING_SCREEN_DIRECTORY,
    LOAD_BAR_DIRT_DIRECTORY,
    LOAD_BAR_GRASS_DIRECTORY,
    LOAD_BAR_SPROUT_DIRECTORY,
    LOAD_BAR_ZOMBIEHEAD_DIRECTORY,

    CHOOSE_LEVELS_1_DIRECTORY,
    CHOOSE_LEVELS_2_DIRECTORY,
    BACK_BUTTON_DIRECTORY,
    BACK_PRESS_BUTTON_DIRECTORY,
    COMPLETED_DIRECTORY,
    CONTAINER_DIRECTORY,
    DAY_DIRECTORY,
    DAY_LIT_DIRECTORY,
    NAME_DIRECTORY,
    NIGHT_DIRECTORY,
    NIGHT_LIT_DIRECTORY,
    SELECTOR_DIRECTORY,
    SELECTOR_BLINK_DIRECTORY,
    STONE_DIRECTORY,
    THUMB_BG_DAY_DIRECTORY,
    THUMB_BG_NIGHT_DIRECTORY,
    NORMAL_DIRECTORY,
    FLAG_DIRECTORY,
    CONE_DIRECTORY,
    BUCKET_DIRECTORY,
    DOOR_DIRECTORY,

    BACKGROUND_LV0_DIRECTORY,
    BACKGROUND_LV1_DIRECTORY,
    BACKGROUND_LV2_DIRECTORY,
    BACKGROUND_DIRECTORY,
    BACKGROUND_NIGHT_DIRECTORY,
    LOSING_MESSAGE_DIRECTORY,

    SUN_DIRECTORY,
    SUN_BAR_DIRECTORY,
    ICON_BAR_DIRECTORY,
    SHOVEL_BAR_DIRECTORY,
    SHOVEL_DIRECTORY,
    FLAG_METER,
    FLAG_METER_PROGRESS,
    FLAG_METER_PART,

    PAUSE_ICON_DIRECTORY,
    PAUSE_ICON_PRESS_DIRECTORY,
    TURBO_ICON_DIRECTORY,
    TURBO_ICON_PRESS_DIRECTORY,
    MENU_DIRECTORY,
    RENAME_MENU_DIRECTORY,
    NEW_USER_DIRECTORY,
    LEAVE_PROMPT_DIRECTORY,
    QUIT_PROMPT_DIRECTORY,
    RESET_PROMPT_DIRECTORY,
    RESTART_PROMPT_DIRECTORY,
    SLIDER_DIRECTORY,
    LOCK_DIRECTORY,
    BUTTON_DIRECTORY,
    BUTTON_BLINK_DIRECTORY,
    BACK_TO_GAME_BUTTON_DIRECTORY,
    BACK_TO_GAME_BUTTON_BLINK_DIRECTORY,

    // NORMAL ZOMBIE---------------------------------------------------
    ZOMBIE_CREDIT1_DIRECTORY,
    ZOMBIE_CREDIT2_DIRECTORY,
    ZOMBIE_ARM_DIRECTORY,
    ZOMBIE_ARM_BLINK_DIRECTORY,

    ZOMBIE_WALK1_DIRECTORY,
    ZOMBIE_WALK2_DIRECTORY,
    ZOMBIE_WALK1_BLINK_DIRECTORY,
    ZOMBIE_WALK2_BLINK_DIRECTORY,

    ZOMBIE_DIE1_DIRECTORY,
    ZOMBIE_DIE2_DIRECTORY,
    ZOMBIE_DIE1_BLINK_DIRECTORY,
    ZOMBIE_DIE2_BLINK_DIRECTORY,
    ZOMBIE_HEAD_DIRECTORY,
    ZOMBIE_HEAD_BLINK_DIRECTORY,
    ZOMBIE_BURNT_DIRECTORY,

    ZOMBIE_EATING_DIRECTORY,
    ZOMBIE_EATING_BLINK_DIRECTORY,

    // ARMLESS ZOMBIE--------------------------------------------------------

    ARMLESS_ZOMBIE_WALK1_DIRECTORY,
    ARMLESS_ZOMBIE_WALK2_DIRECTORY,
    ARMLESS_ZOMBIE_WALK1_BLINK_DIRECTORY,
    ARMLESS_ZOMBIE_WALK2_BLINK_DIRECTORY,
    ARMLESS_ZOMBIE_EATING_DIRECTORY,
    ARMLESS_ZOMBIE_EATING_BLINK_DIRECTORY,

    // FLAG ZOMBIE--------------------------------------------------------

    FLAG_ZOMBIE_WALK1_1_DIRECTORY,
    FLAG_ZOMBIE_WALK2_1_DIRECTORY,
    FLAG_ZOMBIE_WALK1_1_BLINK_DIRECTORY,
    FLAG_ZOMBIE_WALK2_1_BLINK_DIRECTORY,
    FLAG_ZOMBIE_EATING_1_DIRECTORY,
    FLAG_ZOMBIE_EATING_1_BLINK_DIRECTORY,

    FLAG_ZOMBIE_WALK1_2_DIRECTORY,
    FLAG_ZOMBIE_WALK2_2_DIRECTORY,
    FLAG_ZOMBIE_WALK1_2_BLINK_DIRECTORY,
    FLAG_ZOMBIE_WALK2_2_BLINK_DIRECTORY,
    FLAG_ZOMBIE_EATING_2_DIRECTORY,
    FLAG_ZOMBIE_EATING_2_BLINK_DIRECTORY,

    FLAG_ZOMBIE_WALK1_3_DIRECTORY,
    FLAG_ZOMBIE_WALK2_3_DIRECTORY,
    FLAG_ZOMBIE_WALK1_3_BLINK_DIRECTORY,
    FLAG_ZOMBIE_WALK2_3_BLINK_DIRECTORY,
    FLAG_ZOMBIE_EATING_3_DIRECTORY,
    FLAG_ZOMBIE_EATING_3_BLINK_DIRECTORY,

    // CONEHEAD ZOMBIE--------------------------------------------------------
    CONE_DROP_DIRECTORY,
    CONE_DROP_BLINK_DIRECTORY,
    CONE1_DIRECTORY,
    CONE1_BLINK_DIRECTORY,
    CONE2_DIRECTORY,
    CONE2_BLINK_DIRECTORY,
    CONE3_DIRECTORY,
    CONE3_BLINK_DIRECTORY,

    // BUCKETHEAD ZOMBIE--------------------------------------------------------
    BUCKET_DROP_DIRECTORY,
    BUCKET_DROP_BLINK_DIRECTORY,
    BUCKET1_DIRECTORY,
    BUCKET1_BLINK_DIRECTORY,
    BUCKET2_DIRECTORY,
    BUCKET2_BLINK_DIRECTORY,
    BUCKET3_DIRECTORY,
    BUCKET3_BLINK_DIRECTORY,

    // DOOR ZOMBIE--------------------------------------------------------
    DOOR_ZOMBIE_CREDIT1_DIRECTORY,
    DOOR_ZOMBIE_CREDIT2_DIRECTORY,

    DOOR_ZOMBIE_WALK1_1_DIRECTORY,
    DOOR_ZOMBIE_WALK2_1_DIRECTORY,
    DOOR_ZOMBIE_WALK1_1_BLINK_DIRECTORY,
    DOOR_ZOMBIE_WALK2_1_BLINK_DIRECTORY,
    DOOR_ZOMBIE_EATING_1_DIRECTORY,
    DOOR_ZOMBIE_EATING_1_BLINK_DIRECTORY,

    DOOR_ZOMBIE_WALK1_2_DIRECTORY,
    DOOR_ZOMBIE_WALK2_2_DIRECTORY,
    DOOR_ZOMBIE_WALK1_2_BLINK_DIRECTORY,
    DOOR_ZOMBIE_WALK2_2_BLINK_DIRECTORY,
    DOOR_ZOMBIE_EATING_2_DIRECTORY,
    DOOR_ZOMBIE_EATING_2_BLINK_DIRECTORY,

    DOOR_ZOMBIE_WALK1_3_DIRECTORY,
    DOOR_ZOMBIE_WALK2_3_DIRECTORY,
    DOOR_ZOMBIE_WALK1_3_BLINK_DIRECTORY,
    DOOR_ZOMBIE_WALK2_3_BLINK_DIRECTORY,
    DOOR_ZOMBIE_EATING_3_DIRECTORY,
    DOOR_ZOMBIE_EATING_3_BLINK_DIRECTORY,

    //-------------------------------------------------------
    START_READY_DIRECTORY,
    START_SET_DIRECTORY,
    START_PLANT_DIRECTORY,
    HUGE_WAVE_DIRECTORY,
    FINAL_WAVE_DIRECTORY,

    BLACK_SCREEN_DIRECTORY,
    WHITE_SCREEN_DIRECTORY,

    FRONTYARD_C1,
    FRONTYARD_C2,
    FRONTYARD_C3,
    FRONTYARD_C4,
    FRONTYARD_C5,
    FRONTYARD_C6,
    FRONTYARD_C7,
    FRONTYARD_C8,
    FRONTYARD_C9,
    FRONTYARD_R1,
    FRONTYARD_R2,
    FRONTYARD_R3,
    FRONTYARD_R4,
    FRONTYARD_R5,

    WIN_00_DIRECTORY,
    WIN_01_DIRECTORY,
    WIN_02_DIRECTORY,
    WIN_03_DIRECTORY,
    WIN_04_DIRECTORY,
    WIN_05_DIRECTORY,
    WIN_06_DIRECTORY,
    WIN_07_DIRECTORY,
    WIN_08_DIRECTORY,
    WIN_09_DIRECTORY,
    WIN_10_DIRECTORY,
    WIN_11_DIRECTORY,
    WIN_12_DIRECTORY,
    WIN_13_DIRECTORY,
    WIN_14_DIRECTORY,
    WIN_15_DIRECTORY,
    WIN_16_DIRECTORY,
    WIN_17_DIRECTORY,
    WIN_18_DIRECTORY,
    WIN_19_DIRECTORY,
    WIN_20_DIRECTORY,
    WIN_21_DIRECTORY,
    WIN_22_DIRECTORY,
    WIN_23_DIRECTORY,
    WIN_24_DIRECTORY,
    WIN_25_DIRECTORY,
    WIN_26_DIRECTORY,
    WIN_27_DIRECTORY,
    WIN_28_DIRECTORY,
    WIN_29_DIRECTORY,
    WIN_30_DIRECTORY,
    WIN_31_DIRECTORY,
    WIN_32_DIRECTORY,
    WIN_33_DIRECTORY,
    WIN_34_DIRECTORY,
    WIN_35_DIRECTORY,
    WIN_36_DIRECTORY,
    WIN_37_DIRECTORY,
    WIN_38_DIRECTORY,
    WIN_39_DIRECTORY,
    WIN_40_DIRECTORY,
    WIN_41_DIRECTORY,
    WIN_42_DIRECTORY,
    WIN_43_DIRECTORY,
    WIN_44_DIRECTORY,
    WIN_45_DIRECTORY,
    WIN_46_DIRECTORY,
    WIN_47_DIRECTORY,
    WIN_48_DIRECTORY,
    WIN_49_DIRECTORY,
    WIN_50_DIRECTORY,
    WIN_51_DIRECTORY,
    WIN_52_DIRECTORY,
    WIN_53_DIRECTORY,
    WIN_54_DIRECTORY,
    WIN_55_DIRECTORY,
    WIN_56_DIRECTORY,
    WIN_57_DIRECTORY,
    WIN_58_DIRECTORY,
    WIN_59_DIRECTORY,
    WIN_60_DIRECTORY,
    WIN_61_DIRECTORY,
    WIN_62_DIRECTORY,
    WIN_63_DIRECTORY,
    WIN_64_DIRECTORY,
    WIN_65_DIRECTORY,
    WIN_66_DIRECTORY,
    WIN_67_DIRECTORY,
    WIN_68_DIRECTORY,
    WIN_69_DIRECTORY,
    WIN_70_DIRECTORY,
    WIN_71_DIRECTORY,
    WIN_72_DIRECTORY,
    WIN_73_DIRECTORY,

    MOUSE_CURSOR_DIRECTORY,
    MOWER_DIRECTORY,

    SHADOW_DIRECTORY,
    BULLET_SHADOW_DIRECTORY,
    SOD_ROLL,
    SOD_ROLL_CAP,

    COUNT_USED_DIRECTORY
};

struct Image
{
    /*
    Contain all image directory corresponding
    */
    string img_dir;
    /*
    The number of sheet, column in sprite of images
    */
    int n_sheet, c_sheet;
    int alpha;
    Image(string _dir);
    Image(string _dir, int _n, int _c);
    Image(string _dir, int _n, int _c, int _a);
};

const int front_yard_r = FRONTYARD_R1;
const int front_yard_c = FRONTYARD_C1;
const int win_dir = WIN_00_DIRECTORY;
extern const Image all_img[];